name = "HTTPDownloads"
uuid = "a1e35db8-64d0-4469-a01a-344a959b690d"
authors = ["Chris Foster <chris42f@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
